import ExcelJS from 'exceljs';
const C={navy:'1F4E78',blue:'D9EAF7',green:'E2F0D9',orange:'FCE4D6',red:'F4CCCC',purple:'E4DFEC',yellow:'FFF2CC',gray:'E7E6E6',dark:'203864',white:'FFFFFF'};
const dash='—',money=n=>Number(n||0),dateLabel=iso=>{const[y,m,d]=iso.split('-');return`${d}.${m}.${y}`};
function title(ws,text,last=6){ws.mergeCells(1,1,1,last);const c=ws.getCell(1,1);c.value=text;c.font={bold:true,size:16,color:{argb:C.white}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:C.dark}};c.alignment={vertical:'middle'};ws.getRow(1).height=28;}
function note(ws,row,text,last=6){ws.mergeCells(row,1,row,last);const c=ws.getCell(row,1);c.value=text;c.alignment={wrapText:true,vertical:'top'};c.font={italic:true,color:{argb:'666666'}};ws.getRow(row).height=34;}
function header(row,fill=C.navy){row.eachCell(c=>{c.font={bold:true,color:{argb:C.white}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:fill}};c.alignment={wrapText:true,vertical:'middle'};c.border={bottom:{style:'thin',color:{argb:'B7B7B7'}}};});row.height=30;}
function body(row){row.eachCell(c=>{c.alignment={wrapText:true,vertical:'top'};c.border={bottom:{style:'hair',color:{argb:'D9E1F2'}}};});}
function widths(ws,arr){arr.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.views=[{state:'frozen',ySplit:4}];}
function value(item,src){if(src==='computed.fullName')return[item.transaction?.firstName,item.transaction?.middleName,item.transaction?.lastName].filter(Boolean).join(' ')||dash;if(src==='computed.disputeEur')return item.dispute?.providerCurrency==='EUR'?item.dispute.providerDisputeAmount:dash;if(src==='computed.comment')return item.clientTotal>1?`${item.clientSequence}-й из ${item.clientTotal} диспутов клиента в этом отчёте`:dash;let v=item;for(const p of src.split('.'))v=v?.[p];return v===null||v===undefined||v===''?dash:v;}
function addOverview(wb,a,dl){const ws=wb.addWorksheet('Обзор');title(ws,`Ежедневный отчёт по чарджбекам — ${dl}`);note(ws,2,`${a.providers.map(x=>x.name).join(' + ')}. Все ${a.metrics.totalChargebacks} диспутов получены от провайдеров ${dl}.`);note(ws,4,'[AI_INSIGHT_OVERVIEW]');ws.getCell('A6').value='Общая картина';ws.getCell('A6').font={bold:true,size:13};ws.addRow(['Провайдер','Кол-во ЧБ','Сумма, EUR','Сумма диспута, EUR','Уникальных клиентов']);header(ws.getRow(7));a.providers.forEach(p=>{const r=ws.addRow([p.name,p.count,p.amount,p.disputeAmount,p.uniqueClients]);body(r);r.getCell(3).numFmt=r.getCell(4).numFmt='#,##0.00';});let r=ws.addRow(['Итого',a.metrics.totalChargebacks,a.metrics.totalTransactionAmount,a.metrics.totalProviderDisputeAmount,a.metrics.uniqueClients]);header(r,'5B9BD5');ws.addRow([]);ws.addRow(['[AI_INSIGHT_PROVIDERS]']);ws.mergeCells(ws.rowCount,1,ws.rowCount,5);ws.addRow([]);r=ws.addRow(['Показатель',dl,'Комментарий']);header(r);[['Всего диспутов',a.metrics.totalChargebacks,'—'],['Сумма, EUR',a.metrics.totalTransactionAmount,'по сумме успешных транзакций в нашей системе'],['Средний чек, EUR',a.metrics.averageTransactionAmount,'—'],['Уникальных клиентов',a.metrics.uniqueClients,'по email без учёта регистра'],['Клиентов с более чем 1 диспутом',a.metrics.multiDisputeClients,`из ${a.metrics.uniqueClients}`],['Мерчантов с диспутами',a.metrics.uniqueMerchants,'с учётом настроенных merchant aliases'],['Транзакций к блоку по флоу',a.metrics.totalChargebacks,'по каждой транзакции']].forEach(x=>body(ws.addRow(x)));ws.addRow([]);ws.addRow(['По мерчантам']);r=ws.addRow(['Мерчант','Кол-во ЧБ','Сумма, EUR','Провайдеры','Входят записи мерчанта']);header(r);a.merchants.forEach(m=>body(ws.addRow([m.name,m.count,m.amount,m.providers.join(', '),a.aliases[m.name]?.join(', ')||m.name])));widths(ws,[28,16,18,24,34]);return ws;}
function addCases(wb,a){const ws=wb.addWorksheet('Кейсы');title(ws,'Кейсы — концентрация диспутов и повторные клиенты',8);note(ws,2,'Ниже — детерминированная концентрация внутри текущего отчёта. Исторические повторы заполняются только после подключения history dataset.',8);const reps=a.clients.filter(c=>c.count>1);ws.getCell('A4').value=`Клиенты с несколькими диспутами в отчёте (${reps.length})`;ws.getCell('A4').font={bold:true,size:12};let r=ws.getRow(6);['Клиент (email)','ФИО','Провайдер','Мерчант','Кол-во ЧБ','Сумма, EUR','Карта','Действие'].forEach((v,i)=>r.getCell(i+1).value=v);header(r);reps.forEach(c=>body(ws.addRow([c.email,c.name,c.providers.join(', '),c.merchantGroups.join(', '),c.count,c.amount,c.cards.join(', '),'BLOCK все транзакции'])));ws.addRow([]);ws.addRow(['Повторные клиенты — были в прошлых отчётах']);ws.addRow(['History dataset пока не подключён. Здесь не используются и не копируются старые данные 27.09.']);widths(ws,[28,24,20,24,14,16,22,22]);return ws;}
function addComparison(wb){const ws=wb.addWorksheet('Сравнение');title(ws,'Сравнение с предыдущим отчётом',4);note(ws,2,'History dataset пока не подключён. Лист намеренно не содержит устаревших значений из эталона 27.09.',4);widths(ws,[28,18,18,18]);return ws;}
function addSummary(wb){const ws=wb.addWorksheet('Итог');title(ws,'Итог',1);ws.getCell('A3').value='[AI_INSIGHT_FINAL]';ws.getCell('A3').alignment={wrapText:true,vertical:'top'};ws.getColumn(1).width=120;ws.getRow(3).height=240;return ws;}
function addTransactions(wb,a,config,dl){const ws=wb.addWorksheet('Транзакции (детализация)');const cols=config.sheets.find(s=>s.id==='transactions')?.columns||[];title(ws,`Детализация: ${a.metrics.totalChargebacks} диспутов, полученных ${dl} (${a.providers.map(x=>x.name).join(' + ')})`,Math.max(1,cols.length));note(ws,2,'Синий=транзакция/провайдер. Зелёный=клиент. Оранжевый=сумма/причина. Красный=карта. Фиолетовый=надёжные ID. Все вычисления выполняет JS.',Math.max(1,cols.length));note(ws,3,'Основная валюта — EUR. Не-EUR dispute amount не конвертируется без явно подключённого FX правила.',Math.max(1,cols.length));const hr=ws.getRow(4);cols.forEach((c,i)=>hr.getCell(i+1).value=c.label);header(hr);const groupFill={transaction:C.blue,client:C.green,amount:C.orange,card:C.red,id:C.purple,comment:C.yellow};const defaultGroups=['transaction','transaction','transaction','transaction','transaction','transaction','transaction','transaction','transaction','client','client','client','client','amount','amount','amount','amount','amount','amount','card','card','card','card','card','id','id','comment'];a.rows.forEach((item,ri)=>{const r=ws.getRow(5+ri);cols.forEach((c,ci)=>{const cell=r.getCell(ci+1);cell.value=value(item,c.source);cell.alignment={wrapText:true,vertical:'top'};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:groupFill[defaultGroups[ci]]||'FFFFFF'}};cell.border={bottom:{style:'hair',color:{argb:'D9D9D9'}}};if(c.format==='currency')cell.numFmt='#,##0.00';if(c.format==='datetime')cell.numFmt='dd.mm.yyyy hh:mm';});r.height=34;});const tr=ws.getRow(5+a.rows.length+1);tr.getCell(13).value='Итого';tr.getCell(14).value=a.metrics.totalTransactionAmount;tr.getCell(17).value=a.metrics.totalProviderDisputeAmount;tr.getCell(18).value='сумма диспутов в EUR по провайдерам';tr.font={bold:true};tr.getCell(14).numFmt=tr.getCell(17).numFmt='#,##0.00';const w=cols.map((c,i)=>i===26?52:[0,1,5,6,9,10,17,22].includes(i)?26:[2,3].includes(i)?20:16);widths(ws,w);return ws;}
function addClients(wb,a,dl){const ws=wb.addWorksheet('Клиенты (детализация)');title(ws,`Детализация: ${a.metrics.uniqueClients} клиента с чарджбеками, полученными ${dl}`,10);note(ws,2,'Клиент = email без учёта регистра. Количество и суммы рассчитаны JS из текущего merged dataset.',10);let r=ws.getRow(4);['Email','ФИО','Страна','Кол-во ЧБ','Сумма, EUR','Провайдер','Мерчант','Карта','Ранее в отчётах','Действие'].forEach((v,i)=>r.getCell(i+1).value=v);header(r);a.clients.forEach(c=>{r=ws.addRow([c.email||dash,c.name,c.country,c.count,c.amount,c.providers.join(', '),c.merchantGroups.join(', '),c.cards.join(', '),dash,'BLOCK']);body(r);r.getCell(5).numFmt='#,##0.00';});widths(ws,[30,25,12,14,16,20,26,24,45,14]);return ws;}
function addHistory(wb){const ws=wb.addWorksheet('История по кейсам');title(ws,'История чарджбеков клиентов',12);note(ws,2,'History dataset пока не подключён. После подключения master history этот лист будет собираться автоматически.',12);return ws;}
function addCustom(wb,a,s){const ws=wb.addWorksheet(s.name.slice(0,31));title(ws,s.name,5);const source={providers:a.providers,merchants:a.merchants,projects:a.projects,mids:a.mids,clients:a.clients}[s.dataset]||[];const cols=s.columns?.length?s.columns:[{key:'name',label:'Name'},{key:'count',label:'CB'},{key:'amount',label:'Amount'}];const h=ws.getRow(3);cols.forEach((c,i)=>h.getCell(i+1).value=c.label);header(h);source.forEach(x=>body(ws.addRow(cols.map(c=>x[c.key]??dash))));widths(ws,cols.map(()=>22));}
export async function generateReport(a,outputPath,{date,config}){const wb=new ExcelJS.Workbook(),dl=dateLabel(date),enabled=id=>config.sheets.find(s=>s.id===id)?.enabled!==false;if(enabled('overview'))addOverview(wb,a,dl);if(enabled('cases'))addCases(wb,a);if(enabled('comparison'))addComparison(wb);if(enabled('summary'))addSummary(wb);if(enabled('transactions'))addTransactions(wb,a,config,dl);if(enabled('clients'))addClients(wb,a,dl);if(enabled('history'))addHistory(wb);for(const s of config.customSheets||[])if(s.enabled!==false)addCustom(wb,a,s);await wb.xlsx.writeFile(outputPath);}
